name: Publish Docker image

# on:
#   push:
#     branches: [ "main" ]
on:
  push:
    tags:
      - 'v*'
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out the repo
        uses: actions/checkout@v3
      # Get docker meta data
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: seelab/substrate-raiv
      # Log into docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build and push docker image
#       - name: Build and push Docker image
#         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#         with:
#           context: server
#           file: server/Dockerfile
#           push: true
#           tags: seelab/substrate-raiv:${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: server
          file: server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
