name: Build and Package Chrome Extension

on:
  push:
    branches: [ "main" ]
  
jobs:
  publish_to_github_packages:
    name: Build Chrome extension and Publish to Github Packages
    runs-on: ubtun
    steps:
      # Check out repository
      - name: Check out the repo
        uses: actions/checkout@v3
      # Setup .npmrc file
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Install extension dependencies
        run: cd browser_extension && yarn install --frozen-lockfile 
      - name: Build extension
        run: yarn build
      - name: Compress extension
        run: zip -rj raiv.zip dist/*
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.1
          release_name: raiv
          draft: true
          prerelease: false

# cd browser_extension && yarn install --frozen-lockfile
# yarn build
# cd dist
# zip -r raiv.zip *

# name: Publish Docker image

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
      
#       - name: Log in to Docker Hub
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
      
#       - name: Build and push Docker image
#         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#         with:
#           context: server
#           file: server/Dockerfile
#           push: true
#           tags: seelab/substrate-raiv:latest
