name: Build and Package Chrome Extension

on:
  push:
    tags:
      - '*'
jobs:
  publish_to_github_packages:
    name: Build Chrome extension and Publish to Github Packages
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Check out the repo
        uses: actions/checkout@v3
      # Setup .npmrc file
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      # Install dependencies
      - name: Install extension dependencies
        run: cd browser_extension && yarn install --frozen-lockfile 
      # Build extension
      - name: Build extension
        run: cd browser_extension && yarn build
      # Compress build
      - name: Compress extension
        run: cd browser_extension/dist && zip -r raiv.zip *
      # Create Release name
      - name: Set env
        run: echo "RELEASE_NAME='RAIV ${{ github.ref_name }}'}/" >> $GITHUB_ENV
      # Create draft release
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: false
      # Add zip as asset to draft release
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./browser_extension/dist/raiv.zip
          asset_name: raiv.zip
          asset_content_type: application/zip
      # Publish release
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
